env:
  - name: WAREHOUSE_ID
    valueFrom: "sql-warehouse"
  - name: REVIEWS_TABLE
    valueFrom: "table"
  - name: RDS_REVIEWS_TABLE
    valueFrom: "table-2"
  - name: SYNC_STATE_TABLE
    valueFrom: "table-3"
